import type {
  AssetRefs,
  BannerSummary,
  CaptureMode,
  DisplayRecord,
  GachaRuleView,
  ItemKind,
  PoolKind,
  PoolKindSummary,
  Profile,
  RecordDerived,
  RecordFilterOptions,
  RateUpResult,
  ResolvedBanner,
  RollBucket,
  TimeStats,
} from "./types";

export const mockProfile: Profile = {
  name: "default",
  created_at: "0",
  updated_at: "0",
  active: true,
};

const mockItemAssetRefs: Record<string, AssetRefs> = {
  rare_1: {
    portrait: "/Game/UI/UI/Gacha/YH_lihui_character_anhunqu.YH_lihui_character_anhunqu",
    icon: "/Game/UI/UI_Icon/Character/Sigrid.Sigrid",
  },
  rare_item_1: {
    icon: "/Game/UI/UI_Icon/Item/rare_item_1.rare_item_1",
  },
  fork_1: {
    portrait: "/Game/UI/UI_Icon/Fork/1024/fork_Rose.fork_Rose",
    icon: "/Game/UI/UI_Icon/Fork/256/fork_Rose.fork_Rose",
  },
};

export const mockRecords: DisplayRecord[] = [
  {
    record_id: "mock-5",
    source_order: 4,
    record_type: "monopoly",
    time: "2026-01-10 18:05:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "rare_item_1",
    item_name: "Golden Upgrade Core",
    item_asset_refs: mockItemAssetRefs.rare_item_1,
    item_kind: "inventory",
    rarity: 5,
    count: 1,
    roll_points: 75,
    roll_label: "75",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-5", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 147,
      pullNoInBanner: 75,
      pity5Before: 74,
      pity5After: 75,
      tenPullProgressAfter: 7,
      hitRarity: null,
      rateUpResult: "not_applicable",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-4",
    source_order: 3,
    record_type: "monopoly",
    time: "2026-01-09 21:40:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "rare_1",
    item_name: "Sigrid",
    item_asset_refs: mockItemAssetRefs.rare_1,
    item_kind: "character",
    rarity: 5,
    count: 1,
    roll_points: 74,
    roll_label: "74",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-4", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 146,
      pullNoInBanner: 74,
      pity5Before: 73,
      pity5After: 74,
      tenPullProgressAfter: 6,
      hitRarity: 5,
      rateUpResult: "up",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-3",
    source_order: 2,
    record_type: "monopoly",
    time: "2026-01-08 19:22:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "common_2",
    item_name: "Training Log",
    item_asset_refs: {},
    item_kind: "inventory",
    rarity: 3,
    count: 1,
    roll_points: 73,
    roll_label: "73",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-3", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 145,
      pullNoInBanner: 73,
      pity5Before: 72,
      pity5After: 73,
      tenPullProgressAfter: 5,
      hitRarity: 3,
      rateUpResult: "unknown",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-2",
    source_order: 1,
    record_type: "fork",
    time: "2026-01-07 20:11:00",
    pool_kind: "fork_lottery",
    pool_id: "ForkLottery_AnHunQu",
    pool_label: "Arc Research",
    banner: mockBanner("ForkLottery_AnHunQu", "fork_lottery", "fork", "Arc Research"),
    item_id: "fork_1",
    item_name: "Rose",
    item_asset_refs: mockItemAssetRefs.fork_1,
    item_kind: "fork",
    rarity: 5,
    count: 1,
    roll_points: 24,
    roll_label: "24",
    roll_bucket: "not_applicable",
    fork_result_mark: "win",
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-2", {
      bannerId: "ForkLottery_AnHunQu",
      poolKind: "fork_lottery",
      pullNoInPoolKind: 24,
      pullNoInBanner: 24,
      pity5Before: 23,
      pity5After: 24,
      tenPullProgressBefore: 4,
      tenPullProgressAfter: 0,
      hitRarity: 5,
      rateUpResult: "up",
      guarantee5Before: true,
      guarantee5After: false,
      ruleId: "fork_lottery_s",
    }),
  },
];

export type MockRecord = (typeof mockRecords)[number];

function mockBanner(
  bannerId: string,
  poolKind: PoolKind,
  bannerType: "limited" | "standard" | "fork",
  title: string,
): ResolvedBanner {
  const limitedAssetRefs: AssetRefs = {
    image: "/Game/UI/UI/Gacha/Activityillustate/YH_UI_choukahuodong_xinzheng03.YH_UI_choukahuodong_xinzheng03",
    featured_portraits: ["/Game/UI/UI/Gacha/YH_lihui_character_anhunqu.YH_lihui_character_anhunqu"],
  };
  const forkAssetRefs: AssetRefs = {
    background: "/Game/UI/UI/ForkShop/UI_YH_Shoppingmall_hupandibanahqbg.UI_YH_Shoppingmall_hupandibanahqbg",
    icon: "/Game/UI/UI_Icon/Fork/1024/fork_Rose.fork_Rose",
  };
  return {
    banner_id: bannerId,
    pool_kind: poolKind,
    banner_type: bannerType,
    title,
    rate_up_5: [],
    rate_up_4: [],
    standard_5_pool: [],
    standard_4_pool: [],
    rule_id: poolKind === "fork_lottery" ? "fork_lottery_s" : poolKind,
    asset_refs: bannerType === "fork" ? forkAssetRefs : limitedAssetRefs,
  };
}

function mockRule(poolKind: PoolKind, ruleId: string): GachaRuleView {
  return {
    rule_id: ruleId,
    pool_kind: poolKind,
    hard_pity_5: poolKind === "fork_lottery" ? 60 : 90,
    hard_up_pity_5: poolKind === "fork_lottery" ? 80 : null,
    pickup_win_rate_5: poolKind === "fork_lottery" ? 25 : null,
    has_guarantee_5: poolKind === "fork_lottery" ? true : false,
    guarantee_scope: poolKind === "fork_lottery" ? "pool_kind" : "unknown",
    carry_scope: "pool_kind",
  };
}

function mockDerived(
  recordId: string,
  options: {
    bannerId: string;
    poolKind: PoolKind;
    countsAsPull?: boolean;
    globalPullNo?: number | null;
    pullNoInPoolKind: number | null;
    pullNoInBanner: number | null;
    pity5Before: number;
    pity5After: number;
    tenPullProgressBefore?: number | null;
    tenPullProgressAfter: number | null;
    hitRarity: number | null;
    rateUpResult: RateUpResult;
    pityBadge?: RecordDerived["pity_badge"];
    guarantee5Before: boolean;
    guarantee5After: boolean;
    ruleId: string;
  },
): RecordDerived {
  return {
    record_id: recordId,
    banner_id: options.bannerId,
    banner_version: null,
    counts_as_pull: options.countsAsPull ?? true,
    global_pull_no: options.countsAsPull === false ? null : (options.globalPullNo ?? options.pullNoInPoolKind),
    pull_no_in_pool_kind: options.pullNoInPoolKind,
    pull_no_in_banner: options.pullNoInBanner,
    pity_5_before: options.pity5Before,
    pity_5_after: options.pity5After,
    ten_pull_progress_before: options.tenPullProgressBefore ?? options.tenPullProgressAfter,
    ten_pull_progress_after: options.tenPullProgressAfter,
    hit_rarity: options.hitRarity,
    rate_up_result: options.rateUpResult,
    pity_badge: options.pityBadge ?? null,
    guarantee_5_before: options.guarantee5Before,
    guarantee_5_after: options.guarantee5After,
    fork_up_pity_before: options.poolKind === "fork_lottery" ? options.pity5Before : null,
    fork_up_pity_after: options.poolKind === "fork_lottery" ? options.pity5After : null,
    fork_forced_up: options.poolKind === "fork_lottery" && options.hitRarity === 5 && options.rateUpResult === "up" ? false : null,
    rule: mockRule(options.poolKind, options.ruleId),
  };
}

export const mockFilterOptions: RecordFilterOptions = {
  banners: [
    { banner_id: "limited_mock", pool_kind: "monopoly_limited", title: "Limited Board", count: 146 },
    { banner_id: "ForkLottery_AnHunQu", pool_kind: "fork_lottery", title: "Arc Research", count: 36 },
  ],
  roll_buckets: [
    { bucket: "gift", count: 0 },
    { bucket: "sleep", count: 0 },
    { bucket: "1", count: 0 },
    { bucket: "2", count: 0 },
    { bucket: "3", count: 0 },
    { bucket: "4", count: 0 },
    { bucket: "5", count: 0 },
    { bucket: "6", count: 0 },
    { bucket: "not_applicable", count: 3 },
  ] satisfies { bucket: RollBucket; count: number }[],
  item_kinds: [
    { item_kind: "character", count: 1 },
    { item_kind: "fork", count: 1 },
    { item_kind: "appearance", count: 0 },
    { item_kind: "inventory", count: 1 },
    { item_kind: "vehicle_module", count: 0 },
    { item_kind: "unknown", count: 0 },
  ] satisfies { item_kind: ItemKind; count: number }[],
};

export const mockCaptureSessions = new Map<
  string,
  { profileName: string; polls: number; stopped: boolean; mode: CaptureMode }
>();

export const mockSummary: PoolKindSummary[] = [
  {
    pool_kind: "monopoly_limited",
    label: "Limited Board",
    total_pulls: 147,
    roll_points_total: 10806,
    known_roll_point_records: 147,
    missing_roll_point_records: 0,
    hit_count: 2,
    five_star_item_count: 3,
    current_pity: 75,
    current_ten_pull_progress: 7,
    current_guarantee: false,
    hard_pity: 90,
    average_5star_pity: 72.5,
    average_4star_pity: 10,
    min_5star_pity: 71,
    max_5star_pity: 74,
    early_hit_count: 2,
    up_count: 2,
    off_rate_count: 0,
    not_applicable_rate_up_count: 0,
    unknown_rate_up_count: 0,
    observed_up_rate: 1,
    fork_win_count: 0,
    fork_loss_count: 0,
    fork_forced_up_count: 0,
    fork_observed_25_75_win_rate: null,
    latest_5star: mockRecords[1],
    latest_5star_any: mockRecords[0],
    four_star_count: 8,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 8,
    average_roll_points_to_5star: 72.5,
    roll_point_cost_samples_5star: 2,
  },
  {
    pool_kind: "fork_lottery",
    label: "Arc Research",
    total_pulls: 36,
    roll_points_total: 666,
    known_roll_point_records: 36,
    missing_roll_point_records: 0,
    hit_count: 1,
    five_star_item_count: 1,
    current_pity: 12,
    current_ten_pull_progress: 0,
    current_guarantee: false,
    hard_pity: 60,
    average_5star_pity: 24,
    average_4star_pity: 10,
    min_5star_pity: 24,
    max_5star_pity: 24,
    early_hit_count: 1,
    up_count: 1,
    off_rate_count: 0,
    not_applicable_rate_up_count: 0,
    unknown_rate_up_count: 0,
    observed_up_rate: 1,
    fork_win_count: 1,
    fork_loss_count: 0,
    fork_forced_up_count: 0,
    fork_observed_25_75_win_rate: 1,
    latest_5star: mockRecords[3],
    latest_5star_any: mockRecords[3],
    four_star_count: 1,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 1,
    average_roll_points_to_5star: 24,
    roll_point_cost_samples_5star: 1,
  },
];

export const mockBanners: BannerSummary[] = [
  {
    banner_id: "limited_mock",
    pool_id: "CardPool_Character",
    pool_kind: "monopoly_limited",
    banner_type: "limited",
    title: "Limited Board",
    version: null,
    start_at: null,
    end_at: null,
    asset_refs: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board").asset_refs,
    total_pulls: 147,
    roll_points_total: 10806,
    known_roll_point_records: 147,
    missing_roll_point_records: 0,
    five_star_count: 2,
    four_star_count: 8,
    current_5star_pity: 73,
    average_5star_pity: 72.5,
    rate_up_5_count: 2,
    off_rate_5_count: 0,
    not_applicable_rate_up_5_count: 0,
    unknown_rate_up_5_count: 0,
    fork_win_count: 0,
    fork_loss_count: 0,
    fork_forced_up_count: 0,
    fork_observed_25_75_win_rate: null,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 8,
    average_roll_points_to_5star: 72.5,
    roll_point_cost_samples_5star: 2,
    latest_hit: mockRecords[1],
  },
  {
    banner_id: "ForkLottery_AnHunQu",
    pool_id: "ForkLottery_AnHunQu",
    pool_kind: "fork_lottery",
    banner_type: "fork",
    title: "Arc Research",
    version: null,
    start_at: null,
    end_at: null,
    asset_refs: mockBanner("ForkLottery_AnHunQu", "fork_lottery", "fork", "Arc Research").asset_refs,
    total_pulls: 36,
    roll_points_total: 666,
    known_roll_point_records: 36,
    missing_roll_point_records: 0,
    five_star_count: 1,
    four_star_count: 1,
    current_5star_pity: 12,
    average_5star_pity: 24,
    rate_up_5_count: 1,
    off_rate_5_count: 0,
    not_applicable_rate_up_5_count: 0,
    unknown_rate_up_5_count: 0,
    fork_win_count: 1,
    fork_loss_count: 0,
    fork_forced_up_count: 0,
    fork_observed_25_75_win_rate: 1,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 1,
    average_roll_points_to_5star: 24,
    roll_point_cost_samples_5star: 1,
    latest_hit: mockRecords[3],
  },
];

export const mockTimeStats: TimeStats = {
  monthly: [
    {
      bucket: "2026-01",
      total_pulls: 182,
      five_star_count: 3,
      four_star_count: 9,
      roll_points_total: 11397,
      known_roll_point_records: 182,
      missing_roll_point_records: 0,
      average_5star_pity: 56.3,
    },
  ],
  daily: [
    {
      bucket: "2026-01-09",
      total_pulls: 1,
      five_star_count: 1,
      four_star_count: 0,
      roll_points_total: 74,
      known_roll_point_records: 1,
      missing_roll_point_records: 0,
      average_5star_pity: 74,
    },
  ],
  missing_time_records: 0,
};
