import type {
  AssetRefs,
  BannerSummary,
  CaptureMode,
  DisplayRecord,
  GachaRuleView,
  PoolKind,
  PoolKindSummary,
  Profile,
  RecordDerived,
  RecordFilterOptions,
  RateUpResult,
  ResolvedBanner,
  ResourceSummary,
  TimeStats,
} from "./types";

export const mockProfile: Profile = {
  name: "default",
  created_at: "0",
  updated_at: "0",
  active: true,
};

export const mockItemAssetRefs: Record<string, AssetRefs> = {
  rare_1: {
    portrait: "/Game/UI/UI/Gacha/YH_lihui_character_anhunqu.YH_lihui_character_anhunqu",
    icon: "/Game/UI/UI_Icon/Character/Sigrid.Sigrid",
  },
  fork_1: {
    portrait: "/Game/UI/UI_Icon/Fork/1024/fork_Rose.fork_Rose",
    icon: "/Game/UI/UI_Icon/Fork/256/fork_Rose.fork_Rose",
  },
};

export const mockRecords: DisplayRecord[] = [
  {
    record_id: "mock-4",
    record_type: "monopoly",
    time: "2026-01-09 21:40:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board", "curated"),
    item_id: "rare_1",
    item_name: "Sigrid",
    item_asset_refs: mockItemAssetRefs.rare_1,
    rarity: 5,
    count: 1,
    roll_points: 74,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-4", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 146,
      pullNoInBanner: 74,
      pity5Before: 73,
      pity5After: 0,
      pity4Before: 4,
      pity4After: 5,
      hitRarity: 5,
      rateUpResult: "up",
      confidence: "curated",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-3",
    record_type: "monopoly",
    time: "2026-01-08 19:22:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board", "curated"),
    item_id: "common_2",
    item_name: "Training Log",
    item_asset_refs: {},
    rarity: 3,
    count: 1,
    roll_points: 73,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-3", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 145,
      pullNoInBanner: 73,
      pity5Before: 72,
      pity5After: 73,
      pity4Before: 3,
      pity4After: 4,
      hitRarity: null,
      rateUpResult: "unknown",
      confidence: "unknown",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-2",
    record_type: "fork",
    time: "2026-01-07 20:11:00",
    pool_kind: "fork_lottery",
    pool_id: "ForkLottery_AnHunQu",
    pool_label: "Arc Research",
    banner: mockBanner("ForkLottery_AnHunQu", "fork_lottery", "fork", "Arc Research", "exact"),
    item_id: "fork_1",
    item_name: "Rose",
    item_asset_refs: mockItemAssetRefs.fork_1,
    rarity: 5,
    count: 1,
    roll_points: 24,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-2", {
      bannerId: "ForkLottery_AnHunQu",
      poolKind: "fork_lottery",
      pullNoInPoolKind: 24,
      pullNoInBanner: 24,
      pity5Before: 23,
      pity5After: 0,
      pity4Before: 6,
      pity4After: 7,
      hitRarity: 5,
      rateUpResult: "up",
      confidence: "exact",
      guarantee5Before: true,
      guarantee5After: false,
      ruleId: "fork_lottery_s",
    }),
  },
];

export function mockBanner(
  bannerId: string,
  poolKind: PoolKind,
  bannerType: "limited" | "standard" | "fork",
  title: string,
  confidence: string,
  phase?: string,
): ResolvedBanner {
  const limitedAssetRefs: AssetRefs = {
    image: "/Game/UI/UI/Gacha/Activityillustate/YH_UI_choukahuodong_xinzheng03.YH_UI_choukahuodong_xinzheng03",
    featured_portraits: ["/Game/UI/UI/Gacha/YH_lihui_character_anhunqu.YH_lihui_character_anhunqu"],
  };
  const forkAssetRefs: AssetRefs = {
    background: "/Game/UI/UI/ForkShop/UI_YH_Shoppingmall_hupandibanahqbg.UI_YH_Shoppingmall_hupandibanahqbg",
    icon: "/Game/UI/UI_Icon/Fork/1024/fork_Rose.fork_Rose",
  };
  return {
    status: "matched",
    reason: "matched",
    banner_id: bannerId,
    pool_kind: poolKind,
    banner_type: bannerType,
    title,
    phase: phase ?? null,
    rate_up_5: [],
    rate_up_4: [],
    rule_id: poolKind === "fork_lottery" ? "fork_lottery_s" : poolKind,
    asset_refs: bannerType === "fork" ? forkAssetRefs : limitedAssetRefs,
    source_confidence: confidence,
  };
}

export function mockRule(poolKind: PoolKind, ruleId: string, confidence: string): GachaRuleView {
  return {
    status: "matched",
    reason: "matched",
    rule_id: ruleId,
    pool_kind: poolKind,
    hard_pity_5: poolKind === "fork_lottery" ? 80 : 90,
    hard_pity_4: null,
    pickup_win_rate_5: poolKind === "fork_lottery" ? 25 : null,
    pickup_win_rate_4: null,
    has_guarantee_5: poolKind === "fork_lottery" ? true : false,
    has_guarantee_4: null,
    guarantee_scope: poolKind === "fork_lottery" ? "pool_kind" : "unknown",
    carry_scope: "pool_kind",
    source_confidence: confidence,
  };
}

export function mockDerived(
  recordId: string,
  options: {
    bannerId: string;
    poolKind: PoolKind;
    pullNoInPoolKind: number;
    pullNoInBanner: number;
    pity5Before: number;
    pity5After: number;
    pity4Before: number;
    pity4After: number;
    hitRarity: number | null;
    rateUpResult: RateUpResult;
    confidence: string;
    guarantee5Before: boolean;
    guarantee5After: boolean;
    ruleId: string;
  },
): RecordDerived {
  return {
    record_id: recordId,
    banner_id: options.bannerId,
    banner_version: null,
    banner_phase: null,
    pull_no_in_pool_kind: options.pullNoInPoolKind,
    pull_no_in_banner: options.pullNoInBanner,
    pity_5_before: options.pity5Before,
    pity_5_after: options.pity5After,
    pity_4_before: options.pity4Before,
    pity_4_after: options.pity4After,
    hit_rarity: options.hitRarity,
    rate_up_result: options.rateUpResult,
    result_confidence: options.confidence,
    guarantee_5_before: options.guarantee5Before,
    guarantee_5_after: options.guarantee5After,
    guarantee_4_before: null,
    guarantee_4_after: null,
    rule: mockRule(options.poolKind, options.ruleId, options.confidence),
  };
}

export const mockFilterOptions: RecordFilterOptions = {
  pools: [
    { pool_id: "CardPool_Character", pool_kind: "monopoly_limited", label: "Limited Board", count: 146 },
    { pool_id: "ForkLottery_AnHunQu", pool_kind: "fork_lottery", label: "Arc Research", count: 36 },
  ],
  banners: [
    { banner_id: "limited_mock", pool_kind: "monopoly_limited", title: "Limited Board", count: 146, phase: null },
    { banner_id: "ForkLottery_AnHunQu", pool_kind: "fork_lottery", title: "Arc Research", count: 36, phase: null },
  ],
  record_types: [
    { record_type: "monopoly", count: 146 },
    { record_type: "fork", count: 36 },
  ],
};

export const mockCaptureSessions = new Map<
  string,
  { profileName: string; polls: number; stopped: boolean; mode: CaptureMode }
>();

export const mockSummary: PoolKindSummary[] = [
  {
    pool_kind: "monopoly_limited",
    label: "Limited Board",
    total_pulls: 146,
    roll_points_total: 10731,
    known_roll_point_records: 146,
    missing_roll_point_records: 0,
    hit_count: 2,
    current_pity: 73,
    current_guarantee: false,
    hard_pity: 90,
    average_5star_pity: 72.5,
    min_5star_pity: 71,
    max_5star_pity: 74,
    early_hit_count: 2,
    up_count: 2,
    off_rate_count: 0,
    not_applicable_rate_up_count: 0,
    unknown_rate_up_count: 0,
    observed_up_rate: 1,
    latest_5star: mockRecords[0],
    current_4star_pity: 4,
    hard_pity_4: null,
    average_4star_pity: 9.5,
    min_4star_pity: 5,
    max_4star_pity: 14,
    four_star_count: 8,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 8,
    rule_resolution_status: "matched",
    rule_source_confidence: "curated",
    average_roll_points_to_5star: 72.5,
    average_roll_points_to_4star: 9.5,
    roll_point_cost_samples_5star: 2,
    roll_point_cost_samples_4star: 8,
  },
  {
    pool_kind: "fork_lottery",
    label: "Arc Research",
    total_pulls: 36,
    roll_points_total: 666,
    known_roll_point_records: 36,
    missing_roll_point_records: 0,
    hit_count: 1,
    current_pity: 12,
    current_guarantee: false,
    hard_pity: 80,
    average_5star_pity: 24,
    min_5star_pity: 24,
    max_5star_pity: 24,
    early_hit_count: 1,
    up_count: 1,
    off_rate_count: 0,
    not_applicable_rate_up_count: 0,
    unknown_rate_up_count: 0,
    observed_up_rate: 1,
    latest_5star: mockRecords[2],
    current_4star_pity: 3,
    hard_pity_4: null,
    average_4star_pity: 7,
    min_4star_pity: 7,
    max_4star_pity: 7,
    four_star_count: 1,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 1,
    rule_resolution_status: "matched",
    rule_source_confidence: "exact",
    average_roll_points_to_5star: 24,
    average_roll_points_to_4star: 7,
    roll_point_cost_samples_5star: 1,
    roll_point_cost_samples_4star: 1,
  },
];

export const mockBanners: BannerSummary[] = [
  {
    banner_id: "limited_mock",
    pool_id: "CardPool_Character",
    pool_kind: "monopoly_limited",
    banner_type: "limited",
    title: "Limited Board",
    version: null,
    phase: null,
    start_at: null,
    end_at: null,
    source_confidence: "curated",
    asset_refs: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board", "curated").asset_refs,
    total_pulls: 146,
    roll_points_total: 10731,
    known_roll_point_records: 146,
    missing_roll_point_records: 0,
    five_star_count: 2,
    four_star_count: 8,
    current_5star_pity: 73,
    current_4star_pity: 4,
    average_5star_pity: 72.5,
    average_4star_pity: 9.5,
    rate_up_5_count: 2,
    off_rate_5_count: 0,
    not_applicable_rate_up_5_count: 0,
    unknown_rate_up_5_count: 0,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 8,
    average_roll_points_to_5star: 72.5,
    average_roll_points_to_4star: 9.5,
    roll_point_cost_samples_5star: 2,
    roll_point_cost_samples_4star: 8,
    latest_hit: mockRecords[0],
  },
  {
    banner_id: "ForkLottery_AnHunQu",
    pool_id: "ForkLottery_AnHunQu",
    pool_kind: "fork_lottery",
    banner_type: "fork",
    title: "Arc Research",
    version: null,
    phase: null,
    start_at: null,
    end_at: null,
    source_confidence: "exact",
    asset_refs: mockBanner("ForkLottery_AnHunQu", "fork_lottery", "fork", "Arc Research", "exact").asset_refs,
    total_pulls: 36,
    roll_points_total: 666,
    known_roll_point_records: 36,
    missing_roll_point_records: 0,
    five_star_count: 1,
    four_star_count: 1,
    current_5star_pity: 12,
    current_4star_pity: 3,
    average_5star_pity: 24,
    average_4star_pity: 7,
    rate_up_5_count: 1,
    off_rate_5_count: 0,
    not_applicable_rate_up_5_count: 0,
    unknown_rate_up_5_count: 0,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 1,
    average_roll_points_to_5star: 24,
    average_roll_points_to_4star: 7,
    roll_point_cost_samples_5star: 1,
    roll_point_cost_samples_4star: 1,
    latest_hit: mockRecords[2],
  },
];

export const mockResource: ResourceSummary = {
  total_roll_points: 11397,
  known_roll_point_records: 182,
  missing_roll_point_records: 0,
  by_pool_kind: [
    {
      pool_kind: "monopoly_limited",
      label: "Limited Board",
      roll_points_total: 10731,
      known_roll_point_records: 146,
      missing_roll_point_records: 0,
    },
    {
      pool_kind: "monopoly_standard",
      label: "Standard Board",
      roll_points_total: 0,
      known_roll_point_records: 0,
      missing_roll_point_records: 0,
    },
    {
      pool_kind: "fork_lottery",
      label: "Arc Research",
      roll_points_total: 666,
      known_roll_point_records: 36,
      missing_roll_point_records: 0,
    },
  ],
};

export const mockTimeStats: TimeStats = {
  monthly: [
    {
      bucket: "2026-01",
      total_pulls: 182,
      five_star_count: 3,
      four_star_count: 9,
      roll_points_total: 11397,
      known_roll_point_records: 182,
      missing_roll_point_records: 0,
      average_5star_pity: 56.3,
      average_4star_pity: 9.2,
    },
  ],
  daily: [
    {
      bucket: "2026-01-09",
      total_pulls: 1,
      five_star_count: 1,
      four_star_count: 0,
      roll_points_total: 74,
      known_roll_point_records: 1,
      missing_roll_point_records: 0,
      average_5star_pity: 74,
      average_4star_pity: null,
    },
  ],
  phases: [
    {
      version: null,
      phase: null,
      total_pulls: 182,
      five_star_count: 3,
      four_star_count: 9,
      roll_points_total: 11397,
      known_roll_point_records: 182,
      missing_roll_point_records: 0,
      banner_count: 2,
      average_5star_pity: 56.3,
      average_4star_pity: 9.2,
    },
  ],
  missing_time_records: 0,
};
