import type { BannerSummary, DisplayRecord } from "../types";
import { mockBanner, mockScenario, type MockScenario } from "./common";
import { mockRecords, mockUnknownForkRecord, mockUnknownLimitedRecord } from "./records";

function mockSyntheticBannerSummary(record: DisplayRecord, title: string): BannerSummary {
  return {
    banner_id: record.derived.banner_id ?? "",
    pool_id: record.pool_id,
    pool_kind: record.pool_kind,
    banner_type: record.banner.banner_type,
    resolution_issue: record.banner.resolution_issue,
    title,
    version: null,
    start_at: null,
    end_at: null,
    asset_refs: record.banner.asset_refs,
    total_pulls: 1,
    roll_points_total: record.roll_points ?? 0,
    known_roll_point_records: record.roll_points == null ? 0 : 1,
    missing_roll_point_records: record.roll_points == null ? 1 : 0,
    five_star_count: 0,
    four_star_count: 0,
    current_5star_pity: record.derived.pity_5_after,
    average_5star_pity: null,
    rate_up_5_count: 0,
    off_rate_5_count: 0,
    not_applicable_rate_up_5_count: 0,
    unknown_rate_up_5_count: 0,
    fork_win_count: 0,
    fork_loss_count: 0,
    fork_forced_up_count: 0,
    fork_observed_25_75_win_rate: null,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 0,
    average_roll_points_to_5star: null,
    roll_point_cost_samples_5star: 0,
    latest_hit: null,
  };
}

const mockUnknownBanners: BannerSummary[] = [
  mockSyntheticBannerSummary(mockUnknownForkRecord, "KaesiNew"),
  mockSyntheticBannerSummary(mockUnknownLimitedRecord, "CardPool_Character"),
];

export function mockBannersForScenario(scenario: MockScenario = mockScenario()) {
  return scenario === "unknown-banners" ? [...mockUnknownBanners, ...mockBanners] : mockBanners;
}

const mockBanners: BannerSummary[] = [
  {
    banner_id: "limited_mock",
    pool_id: "CardPool_Character",
    pool_kind: "monopoly_limited",
    banner_type: "limited",
    title: "Limited Board",
    version: null,
    start_at: null,
    end_at: null,
    asset_refs: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board").asset_refs,
    total_pulls: 147,
    roll_points_total: 10806,
    known_roll_point_records: 147,
    missing_roll_point_records: 0,
    five_star_count: 2,
    four_star_count: 8,
    current_5star_pity: 73,
    average_5star_pity: 72.5,
    rate_up_5_count: 2,
    off_rate_5_count: 0,
    not_applicable_rate_up_5_count: 0,
    unknown_rate_up_5_count: 0,
    fork_win_count: 0,
    fork_loss_count: 0,
    fork_forced_up_count: 0,
    fork_observed_25_75_win_rate: null,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 8,
    average_roll_points_to_5star: 72.5,
    roll_point_cost_samples_5star: 2,
    latest_hit: mockRecords[1],
  },
  {
    banner_id: "ForkLottery_AnHunQu",
    pool_id: "ForkLottery_AnHunQu",
    pool_kind: "fork_lottery",
    banner_type: "fork",
    title: "Arc Research",
    version: null,
    start_at: null,
    end_at: null,
    asset_refs: mockBanner("ForkLottery_AnHunQu", "fork_lottery", "fork", "Arc Research").asset_refs,
    total_pulls: 36,
    roll_points_total: 666,
    known_roll_point_records: 36,
    missing_roll_point_records: 0,
    five_star_count: 1,
    four_star_count: 1,
    current_5star_pity: 12,
    average_5star_pity: 24,
    rate_up_5_count: 1,
    off_rate_5_count: 0,
    not_applicable_rate_up_5_count: 0,
    unknown_rate_up_5_count: 0,
    fork_win_count: 1,
    fork_loss_count: 0,
    fork_forced_up_count: 0,
    fork_observed_25_75_win_rate: 1,
    rate_up_4_count: 0,
    off_rate_4_count: 0,
    not_applicable_rate_up_4_count: 0,
    unknown_rate_up_4_count: 1,
    average_roll_points_to_5star: 24,
    roll_point_cost_samples_5star: 1,
    latest_hit: mockRecords[3],
  },
];
