import type { DisplayRecord } from "../types";
import {
  mockBanner,
  mockDerived,
  mockItemAssetRefs,
  mockScenario,
  mockSyntheticBanner,
  type MockScenario,
} from "./common";

export const mockRecords: DisplayRecord[] = [
  {
    record_id: "mock-5",
    source_order: 4,
    record_type: "monopoly",
    time: "2026-01-10 18:05:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "rare_item_1",
    item_name: "Golden Upgrade Core",
    item_asset_refs: mockItemAssetRefs.rare_item_1,
    item_kind: "inventory",
    rarity: 5,
    count: 1,
    roll_points: 75,
    roll_label: "75",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-5", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 147,
      pullNoInBanner: 75,
      pity5Before: 74,
      pity5After: 75,
      tenPullProgressAfter: 7,
      hitRarity: null,
      rateUpResult: "not_applicable",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-4",
    source_order: 3,
    record_type: "monopoly",
    time: "2026-01-09 21:40:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "rare_1",
    item_name: "Sigrid",
    item_asset_refs: mockItemAssetRefs.rare_1,
    item_kind: "character",
    rarity: 5,
    count: 1,
    roll_points: 74,
    roll_label: "74",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-4", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 146,
      pullNoInBanner: 74,
      pity5Before: 73,
      pity5After: 74,
      tenPullProgressAfter: 6,
      hitRarity: 5,
      rateUpResult: "up",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-3",
    source_order: 2,
    record_type: "monopoly",
    time: "2026-01-08 19:22:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "common_2",
    item_name: "Training Log",
    item_asset_refs: {},
    item_kind: "inventory",
    rarity: 3,
    count: 1,
    roll_points: 73,
    roll_label: "73",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-3", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 145,
      pullNoInBanner: 73,
      pity5Before: 72,
      pity5After: 73,
      tenPullProgressAfter: 5,
      hitRarity: 3,
      rateUpResult: "unknown",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-2",
    source_order: 1,
    record_type: "fork",
    time: "2026-01-07 20:11:00",
    pool_kind: "fork_lottery",
    pool_id: "ForkLottery_AnHunQu",
    pool_label: "Arc Research",
    banner: mockBanner("ForkLottery_AnHunQu", "fork_lottery", "fork", "Arc Research"),
    item_id: "fork_1",
    item_name: "Rose",
    item_asset_refs: mockItemAssetRefs.fork_1,
    item_kind: "fork",
    rarity: 5,
    count: 1,
    roll_points: 24,
    roll_label: "24",
    roll_bucket: "not_applicable",
    fork_result_mark: "win",
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-2", {
      bannerId: "ForkLottery_AnHunQu",
      poolKind: "fork_lottery",
      pullNoInPoolKind: 24,
      pullNoInBanner: 24,
      pity5Before: 23,
      pity5After: 24,
      tenPullProgressBefore: 4,
      tenPullProgressAfter: 0,
      hitRarity: 5,
      rateUpResult: "up",
      guarantee5Before: true,
      guarantee5After: false,
      ruleId: "fork_lottery_s",
    }),
  },
];

export type MockRecord = (typeof mockRecords)[number];

export const mockUnknownLimitedRecord: DisplayRecord = {
  record_id: "mock-unknown-limited",
  source_order: 6,
  record_type: "monopoly",
  time: "2026-08-01 10:00:00",
  pool_kind: "monopoly_limited",
  pool_id: "CardPool_Character",
  pool_label: "Limited Board",
  banner: mockSyntheticBanner("CardPool_Character", "CardPool_Character", "monopoly_limited", "limited", null, "outside_known_windows"),
  item_id: "unknown_limited_item",
  item_name: "unknown_limited_item",
  item_asset_refs: {},
  item_kind: "unknown",
  rarity: null,
  count: 1,
  roll_points: 1,
  roll_label: "1",
  roll_bucket: "1",
  fork_result_mark: null,
  secondary_item_asset_refs: {},
  derived: mockDerived("mock-unknown-limited", {
    bannerId: "CardPool_Character",
    poolKind: "monopoly_limited",
    pullNoInPoolKind: 148,
    pullNoInBanner: 1,
    pity5Before: 75,
    pity5After: 76,
    tenPullProgressBefore: 7,
    tenPullProgressAfter: 8,
    hitRarity: null,
    rateUpResult: "unknown",
    guarantee5Before: false,
    guarantee5After: false,
    ruleId: "fallback_monopoly_limited",
  }),
};

export const mockUnknownForkRecord: DisplayRecord = {
  record_id: "mock-unknown-fork",
  source_order: 5,
  record_type: "fork",
  time: "2026-08-01 10:01:00",
  pool_kind: "fork_lottery",
  pool_id: "ForkLottery_KaesiNew",
  pool_label: "ForkLottery_KaesiNew",
  banner: mockSyntheticBanner("ForkLottery_KaesiNew", "ForkLottery_KaesiNew", "fork_lottery", "fork", "KaesiNew", "unknown_pool"),
  item_id: "unknown_fork_item",
  item_name: "unknown_fork_item",
  item_asset_refs: {},
  item_kind: "fork",
  rarity: null,
  count: 1,
  roll_points: 1,
  roll_label: "1",
  roll_bucket: "not_applicable",
  fork_result_mark: null,
  secondary_item_asset_refs: {},
  derived: mockDerived("mock-unknown-fork", {
    bannerId: "ForkLottery_KaesiNew",
    poolKind: "fork_lottery",
    pullNoInPoolKind: 37,
    pullNoInBanner: 1,
    pity5Before: 12,
    pity5After: 13,
    tenPullProgressBefore: 0,
    tenPullProgressAfter: 1,
    hitRarity: null,
    rateUpResult: "unknown",
    guarantee5Before: false,
    guarantee5After: false,
    ruleId: "fallback_fork_lottery",
  }),
};

export function mockRecordsForScenario(scenario: MockScenario = mockScenario()) {
  return scenario === "unknown-banners" ? [mockUnknownForkRecord, mockUnknownLimitedRecord, ...mockRecords] : mockRecords;
}
