import type { DisplayRecord, RateUpResult } from "../types";
import {
  mockBanner,
  mockDerived,
  mockItemAssetRefs,
  mockScenario,
  mockSyntheticBanner,
  type MockScenario,
} from "./common";

export const mockRecords: DisplayRecord[] = [
  {
    record_id: "mock-5",
    source_order: 4,
    record_type: "monopoly",
    time: "2026-01-10 18:05:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "rare_item_1",
    item_name: "Golden Upgrade Core",
    item_asset_refs: mockItemAssetRefs.rare_item_1,
    item_kind: "inventory",
    rarity: 5,
    count: 1,
    roll_points: 75,
    roll_label: "75",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-5", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 147,
      pullNoInBanner: 75,
      pity5Before: 74,
      pity5After: 75,
      tenPullProgressAfter: 7,
      hitRarity: null,
      rateUpResult: "not_applicable",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-4",
    source_order: 3,
    record_type: "monopoly",
    time: "2026-01-09 21:40:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "rare_1",
    item_name: "Sigrid",
    item_asset_refs: mockItemAssetRefs.rare_1,
    item_kind: "character",
    rarity: 5,
    count: 1,
    roll_points: 74,
    roll_label: "74",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-4", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 146,
      pullNoInBanner: 74,
      pity5Before: 73,
      pity5After: 74,
      tenPullProgressAfter: 6,
      hitRarity: 5,
      rateUpResult: "up",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-3",
    source_order: 2,
    record_type: "monopoly",
    time: "2026-01-08 19:22:00",
    pool_kind: "monopoly_limited",
    pool_id: "CardPool_Character",
    pool_label: "Limited Board",
    banner: mockBanner("limited_mock", "monopoly_limited", "limited", "Limited Board"),
    item_id: "common_2",
    item_name: "Training Log",
    item_asset_refs: {},
    item_kind: "inventory",
    rarity: 3,
    count: 1,
    roll_points: 73,
    roll_label: "73",
    roll_bucket: "not_applicable",
    fork_result_mark: null,
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-3", {
      bannerId: "limited_mock",
      poolKind: "monopoly_limited",
      pullNoInPoolKind: 145,
      pullNoInBanner: 73,
      pity5Before: 72,
      pity5After: 73,
      tenPullProgressAfter: 5,
      hitRarity: 3,
      rateUpResult: "unknown",
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: "monopoly_limited",
    }),
  },
  {
    record_id: "mock-2",
    source_order: 1,
    record_type: "fork",
    time: "2026-01-07 20:11:00",
    pool_kind: "fork_lottery",
    pool_id: "ForkLottery_AnHunQu",
    pool_label: "Arc Research",
    banner: mockBanner("ForkLottery_AnHunQu", "fork_lottery", "fork", "Arc Research"),
    item_id: "fork_1",
    item_name: "Rose",
    item_asset_refs: mockItemAssetRefs.fork_1,
    item_kind: "fork",
    rarity: 5,
    count: 1,
    roll_points: 24,
    roll_label: "24",
    roll_bucket: "not_applicable",
    fork_result_mark: "win",
    secondary_item_asset_refs: {},
    derived: mockDerived("mock-2", {
      bannerId: "ForkLottery_AnHunQu",
      poolKind: "fork_lottery",
      pullNoInPoolKind: 24,
      pullNoInBanner: 24,
      pity5Before: 23,
      pity5After: 24,
      tenPullProgressBefore: 4,
      tenPullProgressAfter: 0,
      hitRarity: 5,
      rateUpResult: "up",
      guarantee5Before: true,
      guarantee5After: false,
      ruleId: "fork_lottery_s",
    }),
  },
];

export type MockRecord = (typeof mockRecords)[number];

export const mockLatestFiveCostDistanceForkRecords: DisplayRecord[] = [
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-288",
    sourceOrder: 288,
    time: "2026-01-18 20:00:00",
    pullNo: 288,
    distance: 20,
    rateUpResult: "up",
    forkResultMark: "win",
    itemId: "fork_1",
    itemName: "Rose",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-268",
    sourceOrder: 268,
    time: "2026-01-17 20:00:00",
    pullNo: 268,
    distance: 1,
    rateUpResult: "off_rate",
    forkResultMark: "lose",
    itemId: "fork_off_2",
    itemName: "Off-rate Arc B",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-267",
    sourceOrder: 267,
    time: "2026-01-17 20:00:00",
    pullNo: 267,
    distance: 59,
    rateUpResult: "off_rate",
    forkResultMark: "lose",
    itemId: "fork_off_1",
    itemName: "Off-rate Arc A",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-208",
    sourceOrder: 208,
    time: "2026-01-16 20:00:00",
    pullNo: 208,
    distance: 16,
    rateUpResult: "up",
    forkResultMark: "win",
    itemId: "fork_1",
    itemName: "Rose",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-192",
    sourceOrder: 192,
    time: "2026-01-15 20:00:00",
    pullNo: 192,
    distance: 32,
    rateUpResult: "up",
    forkResultMark: "win",
    itemId: "fork_1",
    itemName: "Rose",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-160",
    sourceOrder: 160,
    time: "2026-01-14 20:00:04",
    pullNo: 160,
    distance: 1,
    rateUpResult: "up",
    forkResultMark: "win",
    itemId: "fork_1",
    itemName: "Rose",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-159",
    sourceOrder: 159,
    time: "2026-01-14 20:00:03",
    pullNo: 159,
    distance: 1,
    rateUpResult: "off_rate",
    forkResultMark: "lose",
    itemId: "fork_off_same_159",
    itemName: "Off-rate Arc E",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-158",
    sourceOrder: 158,
    time: "2026-01-14 20:00:02",
    pullNo: 158,
    distance: 1,
    rateUpResult: "off_rate",
    forkResultMark: "lose",
    itemId: "fork_off_same_158",
    itemName: "Off-rate Arc F",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-157",
    sourceOrder: 157,
    time: "2026-01-14 20:00:01",
    pullNo: 157,
    distance: 1,
    rateUpResult: "off_rate",
    forkResultMark: "lose",
    itemId: "fork_off_same_157",
    itemName: "Off-rate Arc G",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-156",
    sourceOrder: 156,
    time: "2026-01-14 20:00:00",
    pullNo: 156,
    distance: 56,
    rateUpResult: "up",
    forkResultMark: "win",
    itemId: "fork_1",
    itemName: "Rose",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-100",
    sourceOrder: 100,
    time: "2026-01-13 20:00:00",
    pullNo: 100,
    distance: 20,
    rateUpResult: "off_rate",
    forkResultMark: "lose",
    itemId: "fork_off_3",
    itemName: "Off-rate Arc C",
  }),
  mockForkCostDistanceRecord({
    recordId: "mock-fork-cost-80",
    sourceOrder: 80,
    time: "2026-01-12 20:00:00",
    pullNo: 80,
    distance: 80,
    rateUpResult: "up",
    forkResultMark: "win",
    itemId: "fork_1",
    itemName: "Rose",
  }),
];

export const mockLatestFiveCostDistanceRecords: DisplayRecord[] = [
  ...mockLatestFiveCostDistanceForkRecords,
  ...mockRecords.filter((record) => record.pool_kind !== "fork_lottery"),
];

const mockLatestFiveCrossBannerForkOffRateRecord = mockCrossBannerRecord({
  recordId: "mock-cross-fork-old-off-rate",
  sourceOrder: 35,
  time: "2026-02-01 20:00:00",
  poolKind: "fork_lottery",
  bannerId: "fork_cross_old",
  bannerTitle: "Old Fork Banner",
  pullNoInPoolKind: 35,
  pullNoInBanner: 35,
  pity5Before: 34,
  itemId: "fork_cross_off_rate",
  itemName: "Old Off-rate Arc",
  itemKind: "fork",
  rateUpResult: "off_rate",
  forkResultMark: "lose",
});

export const mockLatestFiveCrossBannerForkRecord = mockCrossBannerRecord({
  recordId: "mock-cross-fork-new-up",
  sourceOrder: 60,
  time: "2026-02-02 20:00:00",
  poolKind: "fork_lottery",
  bannerId: "fork_cross_new",
  bannerTitle: "New Fork Banner",
  pullNoInPoolKind: 60,
  pullNoInBanner: 20,
  pity5Before: 24,
  itemId: "fork_cross_up",
  itemName: "New UP Arc",
  itemKind: "fork",
  rateUpResult: "up",
  forkResultMark: "win",
});

export const mockLatestFiveCrossBannerCharacterRecord = mockCrossBannerRecord({
  recordId: "mock-cross-character-new-up",
  sourceOrder: 60,
  time: "2026-02-02 20:01:00",
  poolKind: "monopoly_limited",
  bannerId: "limited_cross_new",
  bannerTitle: "New Character Banner",
  pullNoInPoolKind: 60,
  pullNoInBanner: 20,
  pity5Before: 59,
  itemId: "character_cross_up",
  itemName: "New Character",
  itemKind: "character",
  rateUpResult: "up",
  forkResultMark: null,
});

export const mockLatestFiveCrossBannerRecords: DisplayRecord[] = [
  mockLatestFiveCrossBannerCharacterRecord,
  mockLatestFiveCrossBannerForkRecord,
  mockLatestFiveCrossBannerForkOffRateRecord,
];

export const mockUnknownLimitedRecord: DisplayRecord = {
  record_id: "mock-unknown-limited",
  source_order: 6,
  record_type: "monopoly",
  time: "2026-08-01 10:00:00",
  pool_kind: "monopoly_limited",
  pool_id: "CardPool_Character",
  pool_label: "Limited Board",
  banner: mockSyntheticBanner("CardPool_Character", "CardPool_Character", "monopoly_limited", "limited", null, "outside_known_windows"),
  item_id: "unknown_limited_item",
  item_name: "unknown_limited_item",
  item_asset_refs: {},
  item_kind: "unknown",
  rarity: null,
  count: 1,
  roll_points: 1,
  roll_label: "1",
  roll_bucket: "1",
  fork_result_mark: null,
  secondary_item_asset_refs: {},
  derived: mockDerived("mock-unknown-limited", {
    bannerId: "CardPool_Character",
    poolKind: "monopoly_limited",
    pullNoInPoolKind: 148,
    pullNoInBanner: 1,
    pity5Before: 75,
    pity5After: 76,
    tenPullProgressBefore: 7,
    tenPullProgressAfter: 8,
    hitRarity: null,
    rateUpResult: "unknown",
    guarantee5Before: false,
    guarantee5After: false,
    ruleId: "fallback_monopoly_limited",
  }),
};

export const mockUnknownForkRecord: DisplayRecord = {
  record_id: "mock-unknown-fork",
  source_order: 5,
  record_type: "fork",
  time: "2026-08-01 10:01:00",
  pool_kind: "fork_lottery",
  pool_id: "ForkLottery_KaesiNew",
  pool_label: "ForkLottery_KaesiNew",
  banner: mockSyntheticBanner("ForkLottery_KaesiNew", "ForkLottery_KaesiNew", "fork_lottery", "fork", "KaesiNew", "unknown_pool"),
  item_id: "unknown_fork_item",
  item_name: "unknown_fork_item",
  item_asset_refs: {},
  item_kind: "fork",
  rarity: null,
  count: 1,
  roll_points: 1,
  roll_label: "1",
  roll_bucket: "not_applicable",
  fork_result_mark: null,
  secondary_item_asset_refs: {},
  derived: mockDerived("mock-unknown-fork", {
    bannerId: "ForkLottery_KaesiNew",
    poolKind: "fork_lottery",
    pullNoInPoolKind: 37,
    pullNoInBanner: 1,
    pity5Before: 12,
    pity5After: 13,
    tenPullProgressBefore: 0,
    tenPullProgressAfter: 1,
    hitRarity: null,
    rateUpResult: "unknown",
    guarantee5Before: false,
    guarantee5After: false,
    ruleId: "fallback_fork_lottery",
  }),
};

export function mockRecordsForScenario(scenario: MockScenario = mockScenario()) {
  if (scenario === "unknown-banners") return [mockUnknownForkRecord, mockUnknownLimitedRecord, ...mockRecords];
  if (scenario === "latest-five-cost-distance") return mockLatestFiveCostDistanceRecords;
  if (scenario === "latest-five-cross-banner") return mockLatestFiveCrossBannerRecords;
  return mockRecords;
}

function mockCrossBannerRecord(options: {
  recordId: string;
  sourceOrder: number;
  time: string;
  poolKind: "monopoly_limited" | "fork_lottery";
  bannerId: string;
  bannerTitle: string;
  pullNoInPoolKind: number;
  pullNoInBanner: number;
  pity5Before: number;
  itemId: string;
  itemName: string;
  itemKind: "character" | "fork";
  rateUpResult: RateUpResult;
  forkResultMark: DisplayRecord["fork_result_mark"];
}): DisplayRecord {
  const isFork = options.poolKind === "fork_lottery";
  const bannerType = isFork ? "fork" : "limited";
  return {
    record_id: options.recordId,
    source_order: options.sourceOrder,
    record_type: isFork ? "fork" : "monopoly",
    time: options.time,
    pool_kind: options.poolKind,
    pool_id: options.bannerId,
    pool_label: options.bannerTitle,
    banner: mockBanner(options.bannerId, options.poolKind, bannerType, options.bannerTitle),
    item_id: options.itemId,
    item_name: options.itemName,
    item_asset_refs: {},
    item_kind: options.itemKind,
    rarity: 5,
    count: 1,
    roll_points: options.pullNoInBanner,
    roll_label: String(options.pullNoInBanner),
    roll_bucket: "not_applicable",
    fork_result_mark: options.forkResultMark,
    secondary_item_asset_refs: {},
    derived: mockDerived(options.recordId, {
      bannerId: options.bannerId,
      poolKind: options.poolKind,
      pullNoInPoolKind: options.pullNoInPoolKind,
      pullNoInBanner: options.pullNoInBanner,
      pity5Before: options.pity5Before,
      pity5After: 0,
      tenPullProgressBefore: options.pullNoInPoolKind % 10,
      tenPullProgressAfter: 0,
      hitRarity: 5,
      rateUpResult: options.rateUpResult,
      guarantee5Before: false,
      guarantee5After: false,
      ruleId: isFork ? "fork_lottery_s" : "monopoly_limited",
    }),
  };
}

function mockForkCostDistanceRecord(options: {
  recordId: string;
  sourceOrder: number;
  time: string;
  pullNo: number;
  distance: number;
  rateUpResult: RateUpResult;
  forkResultMark: DisplayRecord["fork_result_mark"];
  itemId: string;
  itemName: string;
}): DisplayRecord {
  return {
    record_id: options.recordId,
    source_order: options.sourceOrder,
    record_type: "fork",
    time: options.time,
    pool_kind: "fork_lottery",
    pool_id: "ForkLottery_AnHunQu",
    pool_label: "Arc Research",
    banner: mockBanner("ForkLottery_AnHunQu", "fork_lottery", "fork", "Arc Research"),
    item_id: options.itemId,
    item_name: options.itemName,
    item_asset_refs: options.itemId === "fork_1" ? mockItemAssetRefs.fork_1 : {},
    item_kind: "fork",
    rarity: 5,
    count: 1,
    roll_points: options.pullNo,
    roll_label: String(options.pullNo),
    roll_bucket: "not_applicable",
    fork_result_mark: options.forkResultMark,
    secondary_item_asset_refs: {},
    derived: mockDerived(options.recordId, {
      bannerId: "ForkLottery_AnHunQu",
      poolKind: "fork_lottery",
      pullNoInPoolKind: options.pullNo,
      pullNoInBanner: options.pullNo,
      pity5Before: options.distance - 1,
      pity5After: 0,
      tenPullProgressBefore: options.pullNo % 10,
      tenPullProgressAfter: 0,
      hitRarity: 5,
      rateUpResult: options.rateUpResult,
      guarantee5Before: options.forkResultMark === "guaranteed",
      guarantee5After: false,
      ruleId: "fork_lottery_s",
    }),
  };
}
