const DIGIT_TEMPLATE_BYTES: &[(char, &[u8])] = &[
    ('0', include_bytes!("../../assets/page_digits/0_0.png")),
    ('0', include_bytes!("../../assets/page_digits/0_1.png")),
    ('1', include_bytes!("../../assets/page_digits/1_0.png")),
    ('1', include_bytes!("../../assets/page_digits/1_1.png")),
    ('2', include_bytes!("../../assets/page_digits/2_0.png")),
    ('2', include_bytes!("../../assets/page_digits/2_1.png")),
    ('3', include_bytes!("../../assets/page_digits/3_0.png")),
    ('4', include_bytes!("../../assets/page_digits/4_0.png")),
    ('4', include_bytes!("../../assets/page_digits/4_1.png")),
    ('5', include_bytes!("../../assets/page_digits/5_0.png")),
    ('6', include_bytes!("../../assets/page_digits/6_0.png")),
    ('7', include_bytes!("../../assets/page_digits/7_0.png")),
    ('7', include_bytes!("../../assets/page_digits/7_1.png")),
    ('8', include_bytes!("../../assets/page_digits/8_0.png")),
    ('9', include_bytes!("../../assets/page_digits/9_0.png")),
    ('9', include_bytes!("../../assets/page_digits/9_1.png")),
    ('/', include_bytes!("../../assets/page_digits/slash_0.png")),
    ('/', include_bytes!("../../assets/page_digits/slash_1.png")),
];
